"""
Configuration and management of toolchains, projects, builds, and sources for
a build automation system.

This module defines base configurations for toolchains, projects, builds,
build tools, sources, and associated components using SimpleNamespace for
flexible attribute manipulation. It provides predefined structures for build
automation scenarios with configurable commands, paths, platforms, verbs, and
other attributes.

The module leverages fundamental mappings for architecture and platforms to
serve as a foundation for specific build configurations, toolchains, and
source management.

Dependencies:
- os
- platform
- sys
- pathlib
- types

Additionally, custom utilities and snippets from the `share.snippets` module
are imported.

Attributes
----------
gopts : SimpleNamespace
    Global options and configurations, including command-line invocation, host
    platform, current path, toolchains, modules, build actions, and more.

toolchain_base : SimpleNamespace
    Base template for defining toolchains, including their characteristics
    and applicable actions (verbs).

project_base : SimpleNamespace
    Base template for defining projects, including their location, associated
    sources, build configurations, and toolchains.

build_base : SimpleNamespace
    Defines the base attributes for managing build actions, including source
    paths, toolchains, build tools, and other configurable parameters.

buildtool_base : SimpleNamespace
    Base template for defining build tools with associated verbs/actions.

cmake_base : SimpleNamespace
    Configuration template for CMake build tool, defining build options,
    configurations, and generators for different platforms.

scons_base : SimpleNamespace
    Configuration template for SCons build tool, defining associated build
    variables and actions.

source_base : SimpleNamespace
    Template configuration for source definitions, including source types
    and applicable actions.

git_base : SimpleNamespace
    Extended configuration template for Git-based sources, defining git
    repository-specific attributes and actions.

godot_platforms : dict
    Mapping of platform identifiers to their corresponding names in the
    Godot engine.

godot_arch : dict
    Mapping of architecture identifiers to their Godot engine equivalents.

Functions
---------
configure_git(self, config: SimpleNamespace) -> bool
    Applies Git-specific configuration to a provided source configuration.

    Parameters
    ----------
    self : object
        The instance of the class or namespace to which the method is bound.
    config : SimpleNamespace
        The source configuration object to be modified.

    Returns
    -------
    bool
        Returns True upon successful configuration modification.

Notes
-----
The module includes predefined mappings, tools, and actions for ensuring
flexibility in specifying sources, builds, and project configurations while
handling platform- and architecture-specific requirements dynamically.

The `configure_git` function is bound to the `git_base` namespace to provide
runtime configuration capabilities for Git-based sources.
"""
import os.path
import platform
import sys
from pathlib import Path
from types import SimpleNamespace, MethodType

from share.snippets import source_git

gopts = SimpleNamespace(
    command       = " ".join( sys.argv ),      # The command used to run the tool
    platform      = platform.system(),         # The host platform
    path          = Path(os.getcwd()),         # The working path
    modules       = {},                        # The module files for projects
    toolchains    = dict[str,SimpleNamespace](),   # The list of toolchains available on the host machine
    buildtools    = dict[str,SimpleNamespace](),   # The list of buildtools available on the host machine
    projects      = dict[str,SimpleNamespace](),   # The list of projects generated by imported from modules
    sources       = dict[str,SimpleNamespace](),   # Override sources defined on the command line,
    srcdef        = SimpleNamespace(),
    skipkeys      = [  # A list of keys that are skipped when writing out configuration to build scripts.
        'modules',
        'toolchains',
        'buildtools',
        'projects'
    ],
    toolchain_actions = list[str](),
    project_actions   = list[str](),
    build_actions     = list[str](),
    toolchain_verbs   = list[str](),
    project_verbs     = list[str](),
    build_verbs       = list[str]()
)
# MARK: Toolchain
toolchain_base = SimpleNamespace(
    name          =str(),             # The name of the toolchain.
    host          =platform.system(), # The host platform
    verbs         =list[str](),       # keywords presented on the command line that can be used to trigger a functions
    desc          =str(),             # Description of the toolchain
    shell         =list[str](),       # shell command eg. [ "bash", "-c", """ "echo \"shell and script to pass to shell, can be a little awkward to write due to escaping\"" """ ],
    archs         =list[str](),       # List of target architectures eg. ['x86_64', 'arm64'],
    platforms     =list[str](),       # List of target platforms that match values from sys.platform
    skipkeys      =[                  # A list of keys that are skipped when writing out configuration to build scripts.
        'platforms',
        'archs'
    ]
)

# MARK: Project
project_base = SimpleNamespace(
    name          = str(),                         # Set when generated from module as module parent folder.
    path          = Path(),                        #
    verbs         = list[str](),                   #
    sourcedir     = Path(),                        #
    sources       = list[SimpleNamespace](),       #
    buildtools    = list[SimpleNamespace](),       #
    toolchains    = gopts.toolchains.values(),     # default is all of them
    build_configs = dict[str,SimpleNamespace](),   #
    skipkeys      = [                              # A list of keys that are skipped when writing out configuration to build scripts.
        'sources',
        'buildtools',
        'toolchains',
        'build_configs'
    ]
)

# MARK: Build
build_base = SimpleNamespace({**{},**{
    'project'       :SimpleNamespace(), # Is set at project import
    'name'          :str(),
    'script_path'   :Path(),            # is set at project import: project.path / f"{build.name}.py"
    'verbs'         :list[str](),
    'script_parts'  :list(),
    'arch'          :'x86_64',
    'toolchain'     :SimpleNamespace(), # The toolchain used to build the target
    'buildtool'     :SimpleNamespace(),
    'source_dir'    :Path(),            # project relative path to put sources
    'source_path'   :Path(),            # absolute path is set at project import
    'source_def'    :SimpleNamespace(), #
    'disabled'      :False,
    'configure_funcs':list(),
    'skipkeys'      :[  # A list of keys that are skipped when writing out configuration to build scripts.
        'project',
        'toolchain',
        'buildtool',
        'configure_funcs',
        'source_def',
    ],
}})

# MARK: BuildTool
buildtool_base = SimpleNamespace(
    name ='',
    verbs=[],
)

# MARK: Cmake
cmake_base = SimpleNamespace({**vars(buildtool_base), **{
    'name'          :'cmake',
    'verbs'         :['configure','build','clean'],

    # 'toolchain'     :Path(), # Optional key, I rely on it being missing
    'config_type'   :'Debug',
    'config_types'  :{
        'debug'         :'Debug',
        'release'       :"Release",
        'reldeb'        :"RelWithDebInfo",
        # 'relmin'        :"MinSizeRel",
    },
    'config_vars'   :list[str](),

    'generator'     :'Ninja',
    'generators'    :{
        'msvc'          :'Visual Studio 17 2022',
        'ninja'         :'Ninja',
        'ninja-multi'   :'Ninja Multi-Config',
        'mingw'         :'MinGW Makefiles',
    },

    'build_dir'     :'build-cmake',
    'build_vars'    :list[str](),
    'targets'       :list[str](),
    'target'        :str(),
    'skipkeys'      :[  # A list of keys that are skipped when writing out configuration to build scripts.
        'config_types',
        'generators',
        'targets',
    ]
}})

# MARK: SCons
scons_base = SimpleNamespace({**vars(buildtool_base), **{
    'name'          :'scons',
    'verbs'         :['build', 'clean'],
    'build_vars'    :list[str]()
}})

# MARK: SourceDef
source_base = SimpleNamespace(
    name     = str(),
    type     = str(),
    verbs    = list[str](),
    url      = str(),
    skipkeys = [                  # A list of keys that are skipped when writing out configuration to build scripts.
        'configure',
        'expand'
    ]
)

# MARK: Git
git_base = SimpleNamespace({**vars(source_base), **{
    'type'          :'git',
    'remote'        :'origin',
    'verbs'         :['fetch'],
    'url'           :str(),
    'ref'           :'HEAD',
    'gitdir'        :'git', # relative to project path.

}})

# MARK: Arch Mapping
godot_platforms = {
    'android': 'android',
    'ios': 'ios',
    'linux': 'linux',
    'emscripten': 'web',
    'darwin': 'macos',
    'win32': 'windows'
    # aix, cygwin, wasi, are unsupported
}

godot_arch = {
    'armv32': 'arm32',
    'armv7': 'arm32',
    'armeabi-v7a': 'arm32',
    'arm64': 'arm64',
    'arm64-v8a': 'arm64',
    'aarch64': 'arm64',
    'x86_32': 'x86_32',
    'i686': 'x86_32',
    'x86': 'x86_32',
    'x86_64': 'x86_64',
    'wasm32': 'wasm32'
}


def configure_git(self, config: SimpleNamespace) -> bool:
    """
    Configures Git by appending necessary scripts and verbs to the configuration object.

    :param self: Reference to the current instance of the class.
    :param config: A SimpleNamespace object that contains configuration details.
                   It must have `verbs` and `script_parts` attributes as mutable lists.
    :return: A boolean value indicating the success of the configuration process.
    """
    config.verbs.append('source')
    config.script_parts.append(source_git)
    return True


# noinspection PyTypeChecker
setattr( git_base, 'configure', MethodType( configure_git, git_base ) )

